name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ruby:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.3', '2.4', '2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3', '3.4']
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: use older path_expander version
      if:  matrix.ruby == '2.3' || matrix.ruby == '2.4'
      run: echo "gem 'path_expander', '1.1.1'" > Gemfile.local
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: rake spec
      run: bundle exec rake spec
